name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: tyfgyj
      id: tyfgyj
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: tyfgyj
        setup-command: npm install
        command: npm test
        timeout: 2
        max-score: 6
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TYFGYJ_RESULTS: "${{steps.tyfgyj.outputs.result}}"
      with:
        runners: tyfgyj
